Multi-threaded World of Particles: WorldOfParticles.RenderingContext Interface Reference
WorldOfParticles.RenderingContext Interface Reference
Provides rendering context interface for the WorldOfParticles.
Public Member Functions
abstract void onParticleCountChanged (int newParticleCount)
abstract Barrier getBarrier ()
abstract GraphicsConfiguration getGraphicsConfiguration ()
Detailed Description
Provides rendering context interface for the WorldOfParticles.
Definition at line 20 of file WorldOfParticles.java.
Member Function Documentation
abstract Barrier WorldOfParticles.RenderingContext.getBarrier () [pure virtual]
Implemented in JPWorld.
Referenced by WorldOfParticles.getBarrier().
abstract GraphicsConfiguration WorldOfParticles.RenderingContext.getGraphicsConfiguration () [pure virtual]
Implemented in JPWorld.
Referenced by WorldOfParticles.getGraphicsConfiguration().
abstract void WorldOfParticles.RenderingContext.onParticleCountChanged (int newParticleCount) [pure virtual]
Implemented in JPWorld.
Referenced by WorldOfParticles.addNewParticle(), and WorldOfParticles.removeParticle().
The documentation for this interface was generated from the following file:
WorldOfParticles.java